# Fetches royalty-free photos from Wikimedia Commons for the guide.
# Writes JPGs to static/photos and an attribution file to src/lib/photoCredits.ts.
# Run from anywhere: pwsh scripts/fetch-photos.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root "static\photos"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$topics = @(
  @{ q = "Osorno Volcano Chile";                 file = "osorno.jpg" },
  @{ q = "Saltos del Petrohue";                  file = "saltos.jpg" },
  @{ q = "Lago Todos los Santos Petrohue";       file = "todos-los-santos.jpg" },
  @{ q = "Frutillar Teatro del Lago";            file = "frutillar.jpg" },
  @{ q = "Puerto Varas Llanquihue costanera";    file = "puerto-varas.jpg" },
  @{ q = "Iglesia Sagrado Corazon Puerto Varas"; file = "iglesia.jpg" },
  @{ q = "Palafitos Castro Chiloe";              file = "castro.jpg" },
  @{ q = "Lago Llanquihue Osorno";               file = "llanquihue.jpg" },
  @{ q = "Angelmo Puerto Montt";                 file = "puerto-montt.jpg" }
)

$headers = @{ "User-Agent" = "GuiaPuertoVaras/1.0 (personal travel app)" }
$credits = @{}

function Strip-Html([string]$s) {
  if (-not $s) { return "" }
  return ($s -replace "<[^>]+>", "").Trim()
}

foreach ($t in $topics) {
  $dest = Join-Path $outDir $t.file
  if (Test-Path $dest) {
    Write-Host "  = $($t.file): já existe, pulando" -ForegroundColor DarkGray
    continue
  }
  Start-Sleep -Seconds 3  # be gentle with the Wikimedia API (429 rate limit)
  $q = [uri]::EscapeDataString($t.q)
  $api = "https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=search" +
         "&gsrnamespace=6&gsrlimit=12&gsrsearch=$q&prop=imageinfo&iiprop=url|mime|extmetadata&iiurlwidth=1280"
  try {
    $resp = Invoke-RestMethod -Uri $api -Headers $headers
  } catch {
    Write-Host "  ! $($t.file): API falhou ($($_.Exception.Message))" -ForegroundColor Yellow
    continue
  }
  $pages = @()
  if ($resp.query.pages) { $pages = $resp.query.pages.PSObject.Properties.Value | Sort-Object index }

  $chosen = $null
  foreach ($p in $pages) {
    $ii = $p.imageinfo[0]
    if ($ii -and $ii.mime -eq "image/jpeg" -and $ii.thumburl) { $chosen = $ii; break }
  }
  if (-not $chosen) {
    Write-Host "  ! $($t.file): nenhuma JPG encontrada" -ForegroundColor Yellow
    continue
  }

  try {
    Invoke-WebRequest -Uri $chosen.thumburl -OutFile $dest -Headers $headers -UseBasicParsing
  } catch {
    Write-Host "  ! $($t.file): download falhou ($($_.Exception.Message))" -ForegroundColor Yellow
    continue
  }
  $kb = [math]::Round((Get-Item $dest).Length / 1KB)
  $artist = Strip-Html $chosen.extmetadata.Artist.value
  $lic = $chosen.extmetadata.LicenseShortName.value
  $credits[$t.file] = (("{0} — {1} (Wikimedia Commons)" -f $artist, $lic) -replace '"', "'")
  Write-Host ("  OK {0}  {1} KB  [{2}]" -f $t.file, $kb, $lic) -ForegroundColor Green
}

# Emit attribution map for the app.
$lines = $credits.GetEnumerator() | ForEach-Object { "  '$($_.Key)': `"$($_.Value)`"," }
$ts = @"
// Auto-generated by scripts/fetch-photos.ps1 — photo attributions (Wikimedia Commons).
export const photoCredits: Record<string, string> = {
$($lines -join "`n")
};
"@
Set-Content -Path (Join-Path $root "src\lib\photoCredits.ts") -Value $ts -Encoding utf8
Write-Host "`nDone. $($credits.Count) fotos + photoCredits.ts" -ForegroundColor Cyan
